package gg

import org.junit.jupiter.api.Test
import se.alipsa.matrix.core.Matrix
import se.alipsa.matrix.gg.aes.Expression

import static org.junit.jupiter.api.Assertions.*

class ExpressionTest {

  @Test
  void testBasicExpression() {
    def data = Matrix.builder()
        .columnNames(['x', 'y'])
        .rows([[1, 10], [2, 20], [3, 30]])
        .build()

    def expr = new Expression({ it.x * 2 })
    def values = expr.evaluateAll(data)

    assertEquals([2, 4, 6], values)
  }

  @Test
  void testExpressionWithDivision() {
    def data = Matrix.builder()
        .columnNames(['x', 'y'])
        .rows([[1, 10], [2, 20], [4, 40]])
        .build()

    def expr = new Expression({ 1.0 / it.y })
    def values = expr.evaluateAll(data)

    assertEquals(0.1, values[0].doubleValue(), 0.001)
    assertEquals(0.05, values[1].doubleValue(), 0.001)
    assertEquals(0.025, values[2].doubleValue(), 0.001)
  }

  @Test
  void testExpressionReturnsNull() {
    def data = Matrix.builder()
        .columnNames(['x'])
        .rows([[1], [2], [3]])
        .build()

    def expr = new Expression({ null })
    def values = expr.evaluateAll(data)

    assertEquals([null, null, null], values)
  }

  @Test
  void testExpressionThrowsException() {
    def data = Matrix.builder()
        .columnNames(['x'])
        .rows([[1], [2], [3]])
        .build()

    // Closure that throws an exception
    def expr = new Expression({ throw new RuntimeException("Test error") })

    // Should throw wrapped exception
    def ex = assertThrows(RuntimeException) {
      expr.evaluateAll(data)
    }
    assertTrue(ex.message.contains('Expression evaluation failed'))
    assertTrue(ex.message.contains('Test error'))
  }

  @Test
  void testExpressionNullClosure() {
    def ex = assertThrows(IllegalArgumentException) {
      new Expression(null)
    }
    assertTrue(ex.message.contains('cannot be null'))
  }

  @Test
  void testExpressionCustomName() {
    def expr = new Expression({ it.x }, 'myColumn')
    assertEquals('myColumn', expr.name)
  }

  @Test
  void testExpressionAutoGeneratedName() {
    def expr = new Expression({ it.x })
    assertTrue(expr.name.startsWith('.expr.'))
  }

  @Test
  void testAddToMatrixCreatesColumn() {
    def data = Matrix.builder()
        .columnNames(['x', 'y'])
        .rows([[1, 10], [2, 20], [3, 30]])
        .build()

    def expr = new Expression({ it.x + it.y }, 'sum')
    String colName = expr.addToMatrix(data)

    assertEquals('sum', colName)
    assertTrue(data.columnNames().contains('sum'))
    assertEquals([11, 22, 33], data['sum'])
  }

  @Test
  void testAddToMatrixDuplicateColumnName() {
    def data = Matrix.builder()
        .columnNames(['x', 'y'])
        .rows([[1, 10], [2, 20]])
        .build()

    // First expression with name 'computed'
    def expr1 = new Expression({ it.x * 2 }, 'computed')
    String colName1 = expr1.addToMatrix(data)
    assertEquals('computed', colName1)
    assertTrue(data.columnNames().contains('computed'))

    // Second expression with same name should get unique suffix
    def expr2 = new Expression({ it.x * 3 }, 'computed')
    String colName2 = expr2.addToMatrix(data)
    assertEquals('computed_1', colName2)
    assertTrue(data.columnNames().contains('computed_1'))

    // Verify the values are correct
    assertEquals([2, 4], data['computed'])
    assertEquals([3, 6], data['computed_1'])
  }

  @Test
  void testExpressionOf() {
    def expr = Expression.of({ it.x })
    assertNotNull(expr)
    assertTrue(expr.name.startsWith('.expr.'))

    def expr2 = Expression.of({ it.x }, 'named')
    assertEquals('named', expr2.name)
  }

  @Test
  void testExpressionToString() {
    def expr = new Expression({ it.x }, 'myExpr')
    assertEquals('expr(myExpr)', expr.toString())
  }

  @Test
  void testExpressionWithNonNumericConversion() {
    def data = Matrix.builder()
        .columnNames(['x'])
        .rows([[1], [2], [3]])
        .build()

    // Closure returns String that can be converted to Number
    def expr = new Expression({ "${it.x}0" })  // Returns "10", "20", "30"
    def values = expr.evaluateAll(data)

    assertEquals(10, values[0] as int)
    assertEquals(20, values[1] as int)
    assertEquals(30, values[2] as int)
  }

  @Test
  void testExpressionWithInvalidNumericConversion() {
    def data = Matrix.builder()
        .columnNames(['x'])
        .rows([[1], [2]])
        .build()

    def expr = new Expression({ 'abc' })
    def values = expr.evaluateAll(data)

    assertNull(values[0])
    assertNull(values[1])
  }
}
