package se.alipsa.matrix.gg.geom

import groovy.transform.CompileStatic
import se.alipsa.groovy.svg.G
import se.alipsa.matrix.pictura.util.ColorUtil
import se.alipsa.matrix.core.Matrix
import se.alipsa.matrix.core.util.Logger
import se.alipsa.matrix.gg.aes.Aes
import se.alipsa.matrix.gg.aes.Identity
import se.alipsa.matrix.gg.coord.Coord
import se.alipsa.matrix.gg.layer.StatType
import se.alipsa.matrix.gg.scale.Scale

/**
 * Draw a function as a continuous curve.
 *
 * Computes and draws a function as a continuous curve. This makes it easy to
 * superimpose a function on top of an existing plot. The function is called
 * with a grid of evenly spaced values along the x axis, and the results are
 * drawn with a line.
 *
 * Required aesthetics: x, y (generated by stat_function)
 * Optional aesthetics: color, size/linewidth, linetype, alpha
 *
 * Usage:
 * <pre>
 * // Basic function
 * ggplot() + xlim(0, 2*Math.PI) + geom_function(fun: { x -> Math.sin(x) })
 *
 * // With styling
 * ggplot() + xlim(-3, 3) + geom_function(
 *   fun: { x -> x**2 },
 *   color: 'red',
 *   linewidth: 1.5,
 *   linetype: 'dashed'
 * )
 *
 * // Overlay on existing data
 * ggplot(data, aes(x: 'x', y: 'y')) +
 *   geom_point() +
 *   geom_function(fun: { x -> x**2 }, color: 'blue')
 * </pre>
 *
 * @see se.alipsa.matrix.gg.stat.StatsFunction
 */
@CompileStatic
class GeomFunction extends Geom {

  private static final Logger log = Logger.getLogger(GeomFunction)

  /** Line color */
  String color = 'black'

  /** Line width */
  Number size = 0.5

  /** Line type (solid, dashed, dotted, dotdash, longdash, twodash) */
  String linetype = 'solid'

  /** Alpha transparency */
  Number alpha = 1.0

  /** Line end style (butt, round, square) */
  String lineend = 'butt'

  /** Line join style (round, mitre, bevel) */
  String linejoin = 'round'

  GeomFunction() {
    defaultStat = StatType.FUNCTION
    requiredAes = ['x', 'y']
    defaultAes = [color: 'black', size: 0.5, linetype: 'solid'] as Map<String, Object>
  }

  GeomFunction(Map params) {
    this()
    if (params.color) this.color = ColorUtil.normalizeColor(params.color as String)
    if (params.colour) this.color = ColorUtil.normalizeColor(params.colour as String)
    if (params.size != null) this.size = params.size as Number
    if (params.linewidth != null) this.size = params.linewidth as Number
    if (params.linetype) this.linetype = params.linetype as String
    if (params.alpha != null) this.alpha = params.alpha as Number
    if (params.lineend) this.lineend = params.lineend as String
    if (params.linejoin) this.linejoin = params.linejoin as String
    this.params = params
  }

}
