package se.alipsa.matrix.gg.geom

import groovy.transform.CompileStatic
import se.alipsa.groovy.svg.G
import se.alipsa.matrix.charts.util.ColorUtil
import se.alipsa.matrix.core.Matrix
import se.alipsa.matrix.gg.aes.Aes
import se.alipsa.matrix.gg.aes.Identity
import se.alipsa.matrix.gg.coord.Coord
import se.alipsa.matrix.gg.layer.StatType
import se.alipsa.matrix.gg.render.RenderContext
import se.alipsa.matrix.gg.scale.Scale

/**
 * Draw a function as a continuous curve.
 *
 * Computes and draws a function as a continuous curve. This makes it easy to
 * superimpose a function on top of an existing plot. The function is called
 * with a grid of evenly spaced values along the x axis, and the results are
 * drawn with a line.
 *
 * Required aesthetics: x, y (generated by stat_function)
 * Optional aesthetics: color, size/linewidth, linetype, alpha
 *
 * Usage:
 * <pre>
 * // Basic function
 * ggplot() + xlim(0, 2*Math.PI) + geom_function(fun: { x -> Math.sin(x) })
 *
 * // With styling
 * ggplot() + xlim(-3, 3) + geom_function(
 *   fun: { x -> x**2 },
 *   color: 'red',
 *   linewidth: 1.5,
 *   linetype: 'dashed'
 * )
 *
 * // Overlay on existing data
 * ggplot(data, aes(x: 'x', y: 'y')) +
 *   geom_point() +
 *   geom_function(fun: { x -> x**2 }, color: 'blue')
 * </pre>
 *
 * @see se.alipsa.matrix.gg.stat.StatsFunction
 */
@CompileStatic
class GeomFunction extends Geom {

  /** Line color */
  String color = 'black'

  /** Line width */
  Number size = 0.5

  /** Line type (solid, dashed, dotted, dotdash, longdash, twodash) */
  String linetype = 'solid'

  /** Alpha transparency */
  Number alpha = 1.0

  /** Line end style (butt, round, square) */
  String lineend = 'butt'

  /** Line join style (round, mitre, bevel) */
  String linejoin = 'round'

  GeomFunction() {
    defaultStat = StatType.FUNCTION
    requiredAes = ['x', 'y']
    defaultAes = [color: 'black', size: 0.5, linetype: 'solid'] as Map<String, Object>
  }

  GeomFunction(Map params) {
    this()
    if (params.color) this.color = ColorUtil.normalizeColor(params.color as String)
    if (params.colour) this.color = ColorUtil.normalizeColor(params.colour as String)
    if (params.size != null) this.size = params.size as Number
    if (params.linewidth != null) this.size = params.linewidth as Number
    if (params.linetype) this.linetype = params.linetype as String
    if (params.alpha != null) this.alpha = params.alpha as Number
    if (params.lineend) this.lineend = params.lineend as String
    if (params.linejoin) this.linejoin = params.linejoin as String
    this.params = params
  }

  @Override
  void render(G group, Matrix data, Aes aes, Map<String, Scale> scales, Coord coord, RenderContext ctx) {
    if (data == null || data.rowCount() < 2) return

    // stat_function generates columns named 'x' and 'y'
    String xCol = aes.xColName ?: 'x'
    String yCol = aes.yColName ?: 'y'
    String groupCol = aes.groupColName ?: aes.colorColName
    String colorCol = aes.colorColName
    String sizeCol = aes.size instanceof String ? aes.size as String : null
    String alphaCol = aes.alpha instanceof String ? aes.alpha as String : null

    if (xCol == null || yCol == null) {
      throw new IllegalArgumentException("GeomFunction requires x and y aesthetics")
    }

    Scale xScale = scales['x']
    Scale yScale = scales['y']
    Scale colorScale = scales['color']
    Scale sizeScale = scales['size']
    Scale alphaScale = scales['alpha']

    // Group data if a group aesthetic is specified
    Map<Object, List<Map>> groups = new LinkedHashMap<>()  // Preserve insertion order
    data.each { row ->
      def groupKey = groupCol ? row[groupCol] : '__all__'
      if (!groups.containsKey(groupKey)) {
        groups[groupKey] = []
      }
      groups[groupKey] << row.toMap()
    }

    // Warn if multiple groups detected (like R's implementation)
    if (groups.size() > 1) {
      System.err.println("Warning: Multiple drawing groups in geom_function. " +
                        "Did you use the correct group, colour, or fill aesthetics?")
    }

    // Render each group as a separate path
    int elementIndex = 0
    groups.each { groupKey, rows ->
      elementIndex = renderFunction(group, rows, xCol, yCol, colorCol, sizeCol, alphaCol, groupKey,
                     xScale, yScale, colorScale, sizeScale, alphaScale, aes, ctx, elementIndex)
    }
  }

  private int renderFunction(G group, List<Map> rows, String xCol, String yCol,
                              String colorCol, String sizeCol, String alphaCol, Object groupKey,
                              Scale xScale, Scale yScale, Scale colorScale,
                              Scale sizeScale, Scale alphaScale, Aes aes, RenderContext ctx, int elementIndex) {
    // Function data is already in order - DO NOT sort
    List<double[]> points = []
    rows.each { row ->
      def xVal = row[xCol]
      def yVal = row[yCol]

      if (xVal == null || yVal == null) return

      // Transform using scales
      def xTransformed = xScale?.transform(xVal)
      def yTransformed = yScale?.transform(yVal)

      if (xTransformed == null || yTransformed == null) return

      double xPx = xTransformed as double
      double yPx = yTransformed as double

      points << ([xPx, yPx] as double[])
    }

    if (points.size() < 2) return

    // Determine line color
    String lineColor = this.color
    if (colorCol && groupKey != '__all__') {
      if (colorScale) {
        lineColor = colorScale.transform(groupKey)?.toString() ?: this.color
      } else {
        lineColor = GeomUtils.getDefaultColor(groupKey)
      }
    } else if (aes.color instanceof Identity) {
      lineColor = (aes.color as Identity).value.toString()
    }
    lineColor = ColorUtil.normalizeColor(lineColor) ?: lineColor

    Number lineSize = GeomUtils.extractLineSize(this.size, aes, sizeCol, rows, sizeScale)
    Number lineAlpha = GeomUtils.extractLineAlpha(this.alpha, aes, alphaCol, rows, alphaScale)

    // Build SVG path
    StringBuilder d = new StringBuilder()
    double[] first = points[0]
    d << "M ${first[0]} ${first[1]}"

    for (int i = 1; i < points.size(); i++) {
      double[] pt = points[i]
      d << " L ${pt[0]} ${pt[1]}"
    }

    // Create path element
    def path = group.addPath()
        .d(d.toString())
        .fill('none')
        .stroke(lineColor)

    path.addAttribute('stroke-width', lineSize)
    path.addAttribute('stroke-linecap', lineend)
    path.addAttribute('stroke-linejoin', linejoin)

    // Apply line type
    String dashArray = GeomUtils.getDashArray(linetype)
    if (dashArray) {
      path.addAttribute('stroke-dasharray', dashArray)
    }

    // Apply alpha
    if ((lineAlpha as double) < 1.0) {
      path.addAttribute('stroke-opacity', lineAlpha)
    }

    GeomUtils.applyAttributes(path, ctx, 'function', 'gg-function', elementIndex)
    elementIndex++

    return elementIndex
  }
}
