plugins {
  id 'groovy'
}

group = 'se.alipsa.matrix.examples'
version = '1.0.0'

repositories {
  mavenCentral()
  mavenLocal()
}

dependencies {
  implementation libs.groovy
  implementation libs.groovy.ginq
  if (version.contains('SNAPSHOT')) {
    // If we are using snapshot versions of the project we need to
    // depend on the project, otherwise this example will be built before
    // the other project dependencies have been published.
    implementation project(':matrix-core')
    implementation project(':matrix-csv')
    implementation project(':matrix-stats')
    implementation project(':matrix-pict')
  } else {
    // This is what you would if the project was standalone:
    implementation platform('se.alipsa.matrix:matrix-bom:2.6.0')
    implementation 'se.alipsa.matrix:matrix-core'
    implementation 'se.alipsa.matrix:matrix-csv'
    implementation 'se.alipsa.matrix:matrix-stats'
    implementation 'se.alipsa.matrix:matrix-pict'
  }
  testImplementation libs.junit.jupiter
}

test {
  useJUnitPlatform()
}
